# Utiliza una imagen base de Python
FROM python:3.9-slim

# Configura el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios al contenedor
COPY fastapi/requirements.txt ./
COPY fastapi/app_lstm.py ./
COPY fastapi/model_lstm.h5 ./

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto en el que correrá la aplicación
EXPOSE 8000

# Comando para ejecutar la aplicación FastAPI
CMD ["uvicorn", "app_lstm:app", "--host", "0.0.0.0", "--port", "8000"]

