# docker-compose.yml

version: '3.8'
services:
  fastapi:
    build:
      context: ./app/fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  streamlit:
    build:
      context: ./app/streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
